language: php

php:
- 5.6

cache:
  directories:
    - vendor

env:
  global:
  - APP_ENV=local
  - APP_KEY=QkDrgCzGrL7LdJfta2xetcLKVXNSaW5T
  - DB_DATABASE=todo
  - DB_USERNAME=root
  - DB_HOST=127.0.0.1
  matrix:
  - TEST_SUITE=unit
  - TEST_SUITE=integration
  - TEST_SUITE=gui

install:
- composer install --prefer-dist

before_script:
- pip install --user awscli
- aws --version
- mysql -u root -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;"
- php artisan migrate

script: phpunit --testsuite $TEST_SUITE

notifications:
  email:
    recipients:
      secure: rFVee7M8FU1+WS7e9ttIk203NIWj5Eugcnm/syIB4hsaX/ZtePuxs2DsasouzojU0LiiQn8kMZ6Buy+7+NOjnPdSTyJh0eQrMr/5Cn8ZzoA0YIdz09spKqIiYIqxUAh+oQBt38aLeg/ezkbplRtTsV2P3fPDp2JJ5pLF0wge4Co3E1/MsjVEr4Fb60JcdlkGmfMGmcPAH/uheqKb0cHLv82rD+mq4IUdaqAzkNU7As3zZsEfVE7FrzcEy+9lJG199/U1+ilqtsvFX+8drfGZsHOtZ+gMI5I6squcZ7SnT/3Ou+w2OqDMYdlvTw3qUyu7eLPzyTZPgIgCKlJL+LFaYs4XLM/OrxEJBJRyOf702l3ff+Y8YrDUDpR+km4/JoYkAG8I3QT4Alh6beXFy5JJlWvKoWqrNXMqgOs4/ltAtfCilyj1rhgKTMRq9DtvrTUZxRmZcGYDb5zKbfuSfWNtJNNLRtyazQlm0ZA1YTo4ZvHuNdcQprPYAJ3bGRd3aa1R+mLmFoRtGNB9TK7zhBPD9J1iXVJ0lFRWNlCXmH9+YL5+4kw4CAMEdrSecj2y4t49qYN5v//klGlDJa0gB//sxwkobZTHeMlOk5+6fn4jXGJL2AqXTlSJo0OqxctrN3JDQDdT0wTYZXU9H8dPgyYtS2glcQjKOu9eUzgxJA9r7Us=
    on_success: always
    on_failure: always

  slack:
    secure: GuomK9UBeO38+QMxdg9gXDPKLy0DrjM8w5Y5VWjHMcYfXTDhZMuaE/oICQb1R8uWedvRVwM1TmyHU8j8CUl/rL+rHDnNhBmQQ9mDoeejVIcvhRUAYbI+x2UXljtScoVe70P9LwduQU5f28K2Pw/Hc8b2XnTrZoxu0MBp185OH3QggGxB7p3sXg/e1NXuMoZWcjzOTAS6iiOeXyy9RRoGwAYFjIM3z36ZlMEqE+01tQVOonU5tUX9F8Inv2Tu5p1Bbx4UuSgFy/H7FrtylRu+2CI4yLfCgWgIkvUi1MjBgyKtLzaYhTsMMxwQtSPP5gR9CTzi6th1joNokpuuqCdyTnyMq9C7NQYSwiobnjJrAoP2ccjqvMRy9G10STIW9OXTxbkdEQ8LaKXXX3/FVkEnIurN02dLTfyK37pC4ohuTGdrS5GZtcVdd7KPFHAIDyjX80b74rbCFqX/UBMevTBMQquB7chvPAGp6rmTN6r81ZkOPTDN5HU/YLSa45FsL+4nZvqjUGn+eUyhxWUoycMKVhBHtR+vaMNtdJZtG+fveb2EeR4Y9BaH+qF4qkfWw2zqjmEF9xUUSe0xOSgBDu1x2+Q9sxZ0ASM51QvalhgTo63Sidz1vphSqJvdmgwPao2YFakkArw9uHtpnXmo3TOwx5GyqhR8UDYNA6jqXxawN44=
